export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const START_REGISTER = 'START_REGISTER';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const START_LOGIN = 'START_LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';

// Edit Profile
export const INIT_EDIT_PROFILE = 'INIT_EDIT_PROFILE';
export const USERNAME_CHANGE = 'USERNAME_CHANGE';
export const PROFILE_IMAGE_CHANGE = 'PROFILE_IMAGE_CHANGE';
export const SAVE_PROFILE = 'SAVE_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';

// Manage Posts
export const EMPTY_POST_LIST = 'EMPTY_POST_LIST';
export const FILL_POST_LIST = 'FILL_POST_LIST';
export const SELECT_POST_PROFILE = 'SELECT_POST_PROFILE';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';